# -*- coding: utf-8 -*-
"""King County COVID-19 Vaccination Report.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-wNoGYSF1-UFHjB9CcoeMy97r6CJweX1
"""

import pandas as pd

file_path = '/content/sample_data/COVID19-King-County-vax - geography.csv'
df = pd.read_csv(file_path)
print(df.head())

# Columns: geography, population, 2022–2023, 2023–2024, 2024–2025, 2025–2026

year_cols = ["2022-2023", "2023-2024", "2024-2025", "2025-2026"]

df_long = df.melt(
    id_vars=["geography", "population"],
    value_vars=year_cols,
    var_name="year",
    value_name="count"
)
# Optional: clean the year column (e.g., convert "2022–2023" → 2023)
df_long["year"] = df_long["year"].str.split("-").str[0].astype(int)

print(df_long)
from google.colab import files
df_long.to_csv("king_county_vax_long.csv", index=False)
files.download("king_county_vax_long.csv")


file_path = '/content/COVID19-King-County-vax - race_ethnicity.csv'
df = pd.read_csv(file_path)
print(df.head())
# Columns: race_ethnicity, population, 2022–2023, 2023–2024, 2024–2025, 2025–2026

year_cols = ["2022-2023", "2023-2024", "2024-2025", "2025-2026"]

df_long = df.melt(
    id_vars=["race_ethnicity", "population"],
    value_vars=year_cols,
    var_name="year",
    value_name="count"
)


df_long["year"] = df_long["year"].str.split("-").str[0].astype(int)

print(df_long)
from google.colab import files
df_long.to_csv("king_county_ethnicity_long.csv", index=False)
files.download("king_county_ethnicity_long.csv")

import pandas as pd

file_path = '/content/COVID19-King-County-vax - age_group.csv'
df = pd.read_csv(file_path)
print(df.head())

year_cols = ["2022-2023", "2023-2024", "2024-2025", "2025-2026"]

df_long = df.melt(
    id_vars=["age_group", "population"],
    value_vars=year_cols,
    var_name="year",
    value_name="count"
)

df_long["year"] = df_long["year"].str.split("-").str[0].astype(int)

print(df_long)
from google.colab import files
df_long.to_csv("king_county_age_long.csv", index=False)
files.download("king_county_age_long.csv")
